[package]
name = "m2h"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.28", features = ["derive"] }
pulldown-cmark = "0.12.2"
pulldown-cmark-escape = "0.11.0"
syntect = "5.2.0"
syntect-assets = "0.23.6"
serde_json = "1.0"
